* AGitjo

WARNING: This package is very new, and may be unstable!  Please hold off from
using this for now if you expect something more reliable.

-----

AGitjo is a [[https://www.gnu.org/software/emacs/][GNU Emacs]] package that extends Magit with a new menu for AGit-Flow
operations, to make them more convenient for users.  The AGit workflow enables
users to create and edit pull requests using just the "git push" command.  This
package is intended specifically for use with Forgejo-based (e.g. Codeberg)
repositories.

See [[https://forgejo.org/docs/latest/user/agit-support/][Forgejo's documentation about AGit-Flow]] to learn more.

** Installation

Make sure the following dependencies are satisfied before using this package:
- emacs 30.1.
- magit 4.3.8.
- markdown-mode 2.7.
- transient 0.9.1.


This package can be installed with Guix, using the =guix.scm= file in this
repository.  For example, to install to the user profile, one may run the
following in this repository's root directory:
#+begin_src emacs-lisp
  guix package --install-from-file=guix.scm
#+end_src

** Usage

Run the following to load AGitjo:
#+begin_src emacs-lisp
  (use-package agitjo)
#+end_src

Usage generally is as follows:
1. Write and commit some code, and eventually decide it's ready for a pull
   request.
2. Inside the repository, invoke ~agitjo-push~ with =M-x= or the =#= key inside
   a Magit status buffer to open the menu.
3. After setting desired options, invoke one of the push commands to begin a
   git-push operation.
4. If creating a new PR (i.e. when =-f= is disabled), a dedicated buffer will
   open for editing the PR description before pushing.
5. After a satisfactory description is written, confirm that it is completed
   with =C-c C-c= to send it.  This process can also be aborted with =C-c C-k=.
6. Repeat 1-3 with the force-push option (=-f=) enabled to edit the existing PR.
