* AGitjo

WARNING: This package is very new, and may be unstable!  Please hold off from
using this for now if you expect something more reliable.

-----

AGitjo is a [[https://www.gnu.org/software/emacs/][GNU Emacs]] package that provides a transient interface for managing
forge pull requests using AGit-Flow, specifically for Forgejo-based
(e.g. Codeberg) repositories.  This package aims to implement facilities that
make the AGit workflow more convenient for users.

** Installation

This package can be installed with Guix, using the =guix.scm= file in this
repository.  For example, to install to the user profile, one may run the
following in this repository's root directory:
#+begin_src emacs-lisp
  guix package --install-from-file=guix.scm
#+end_src

** Usage

Make sure the following dependencies are satisfied before using this package:
- emacs 30.1.
- magit 4.3.8.
- markdown-mode 2.7.
- transient 0.9.1.


Run the following to load AGitjo:
#+begin_src emacs-lisp
  (use-package agitjo)
#+end_src

Usage generally is as follows:
1. Write some code and commits, then decide it's ready for a pull request.
2. Inside a repository, invoke ~agitjo-push~ with =M-x= or the =#= key inside a
   Magit status buffer.
3. Get prompted for a topic to set.  This is the identifier that is used to
   determine what pull request is being interacted with.  If none is provided,
   the current branch name is used as the topic.  A menu will then open with
   pull request options.
4. After setting desired options, invoke one of the push commands to begin a
   git-push operation.  Currently, only "push current branch to upstream" (=u=)
   is available.
5. If creating a new PR (when =-f= is disabled), a dedicated buffer will open
   for editing the PR description before pushing.
6. After a satisfactory description is written, confirm that it is completed
   with =C-c C-c= to send it.  This process can also be aborted with =C-c C-k=.
7. Repeat 1-4 with the force-push option enabled (=-f=) to edit the existing PR.
